=== juanfcosanz/Xml/XML-Schema/xsd/libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Definimos el esquema-->
<!--Adicionalmente podemos escribir alguna anotacion-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >	
<xs:annotation>
	<xs:documentation>
		Este archivo valida al archivo de libro.xml
	</xs:documentation>
</xs:annotation>

<xs:element name="libros">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="libro" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute type="xs:short" name="paginas" use="optional"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="autor" type="xs:string"/>
						<xs:element name="editorial" type="xs:string"/>
						<xs:element name="precio" type="xs:float"/>
						<xs:element name="fecha" type="xs:integer"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== juanfcosanz/Xml/XML-Schema/libros.xml
<?xml version="1.0" encoding="utf-8"?>
<!--Ligamos en archivo con el XSD en la tag raiz-->
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/libros.xsd">
  <!--como es local , no es nec decir la ubicaion-->
  <libro>
    <nombre paginas="600">El Quijote de la Mancha</nombre>
    <autor>Miguel de Cervantes Savedra</autor>
    <editorial>Una muy vieja</editorial>
    <precio>200.00</precio>
    <fecha>2005</fecha>
  </libro>
  <libro>
    <nombre paginas="400">Cien a√±os de soledad</nombre>
    <autor>Gabriel Garcia Marquez</autor>
    <editorial>Obeja negra</editorial>
    <precio>300.00</precio>
    <fecha>2000</fecha>
  </libro>
  <libro>
    <nombre paginas="200">La guerra del fin del mundo</nombre>
    <autor>Mario Vergas Llosa</autor>
    <editorial>El barco de vapor</editorial>
    <precio>350.00</precio>
    <fecha>2010</fecha>
  </libro>
</libros>
